// <auto-generated />
using EMedia.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMedia.Migrations
{
    [DbContext(typeof(ArtDBContext))]
    [Migration("20260313174922_SubCategoriesAdded")]
    partial class SubCategoriesAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EMedia.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Müzik"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Film"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Tiyatro"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Konser"
                        });
                });

            modelBuilder.Entity("EMedia.Models.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            IsActive = true,
                            Name = "Pop"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            IsActive = true,
                            Name = "Rock"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            IsActive = true,
                            Name = "Jazz"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            IsActive = true,
                            Name = "Blues"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            IsActive = true,
                            Name = "Klasik"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            IsActive = true,
                            Name = "Metal"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            IsActive = true,
                            Name = "Reggae"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            IsActive = true,
                            Name = "Aksiyon"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            IsActive = true,
                            Name = "Dram"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            IsActive = true,
                            Name = "Komedi"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            IsActive = true,
                            Name = "Trajedi"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            IsActive = true,
                            Name = "Komedi"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            IsActive = true,
                            Name = "Dram"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            IsActive = true,
                            Name = "Müzikli Tiyatro"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            IsActive = true,
                            Name = "Klasik Müzik Konserleri"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            IsActive = true,
                            Name = "Halk Müziği Konserleri"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            IsActive = true,
                            Name = "Akustik Konserler"
                        });
                });

            modelBuilder.Entity("EMedia.Models.SubCategory", b =>
                {
                    b.HasOne("EMedia.Models.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EMedia.Models.Category", b =>
                {
                    b.Navigation("SubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
