// <auto-generated />
using System;
using EMedia.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMedia.Migrations
{
    [DbContext(typeof(ArtDBContext))]
    [Migration("20260414175939_IsApprovedAdded")]
    partial class IsApprovedAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EMedia.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Müzik"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Film"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Tiyatro"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Konser"
                        });
                });

            modelBuilder.Entity("EMedia.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CommentId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("EMedia.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DiscountRate")
                        .HasColumnType("int");

                    b.Property<string>("FotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 4, 14, 20, 59, 38, 489, DateTimeKind.Local).AddTicks(9901),
                            FotoPath = "images/pop_album.jpg",
                            IsActive = true,
                            Name = "Pop Albümü - Greatest Hits",
                            Price = 49.90m,
                            Stock = 100,
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 4, 14, 20, 59, 38, 489, DateTimeKind.Local).AddTicks(9922),
                            FotoPath = "images/rock_album.jpg",
                            IsActive = true,
                            Name = "Rock Albümü - Legends of Rock",
                            Price = 59.90m,
                            Stock = 80,
                            SubCategoryId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 4, 14, 20, 59, 38, 489, DateTimeKind.Local).AddTicks(9925),
                            FotoPath = "images/jazz_album.jpg",
                            IsActive = true,
                            Name = "Jazz Albümü - Smooth Jazz Collection",
                            Price = 39.90m,
                            Stock = 60,
                            SubCategoryId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 4, 14, 20, 59, 38, 489, DateTimeKind.Local).AddTicks(9929),
                            FotoPath = "images/blues_album.jpg",
                            IsActive = true,
                            Name = "Blues Albümü - Soulful Blues",
                            Price = 44.90m,
                            Stock = 50,
                            SubCategoryId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 4, 14, 20, 59, 38, 489, DateTimeKind.Local).AddTicks(9931),
                            FotoPath = "images/classical_album.jpg",
                            IsActive = true,
                            Name = "Klasik Albüm - Mozart Collection",
                            Price = 69.90m,
                            Stock = 40,
                            SubCategoryId = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2026, 4, 14, 20, 59, 38, 489, DateTimeKind.Local).AddTicks(9933),
                            FotoPath = "images/metal_album.jpg",
                            IsActive = true,
                            Name = "Metal Albümü - Heavy Metal Anthems",
                            Price = 54.90m,
                            Stock = 70,
                            SubCategoryId = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2026, 4, 14, 20, 59, 38, 489, DateTimeKind.Local).AddTicks(9935),
                            FotoPath = "images/reggae_album.jpg",
                            IsActive = true,
                            Name = "Reggae Albümü - Bob Marley Tribute",
                            Price = 42.90m,
                            Stock = 90,
                            SubCategoryId = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2026, 4, 14, 20, 59, 38, 489, DateTimeKind.Local).AddTicks(9937),
                            FotoPath = "images/action_madmax.jpg",
                            IsActive = true,
                            Name = "Aksiyon Filmi - Mad Max: Fury Road",
                            Price = 89.90m,
                            Stock = 120,
                            SubCategoryId = 8
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2026, 4, 14, 20, 59, 38, 489, DateTimeKind.Local).AddTicks(9939),
                            FotoPath = "images/action_johnwick.jpg",
                            IsActive = true,
                            Name = "Aksiyon Filmi - John Wick",
                            Price = 79.90m,
                            Stock = 100,
                            SubCategoryId = 8
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2026, 4, 14, 20, 59, 38, 489, DateTimeKind.Local).AddTicks(9941),
                            FotoPath = "images/drama_shawshank.jpg",
                            IsActive = true,
                            Name = "Dram Filmi - The Shawshank Redemption",
                            Price = 69.90m,
                            Stock = 80,
                            SubCategoryId = 9
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2026, 4, 14, 20, 59, 38, 489, DateTimeKind.Local).AddTicks(9943),
                            FotoPath = "images/drama_forrestgump.jpg",
                            IsActive = true,
                            Name = "Dram Filmi - Forrest Gump",
                            Price = 74.90m,
                            Stock = 90,
                            SubCategoryId = 9
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2026, 4, 14, 20, 59, 38, 489, DateTimeKind.Local).AddTicks(9945),
                            FotoPath = "images/comedy_mask.jpg",
                            IsActive = true,
                            Name = "Komedi Filmi - The Mask",
                            Price = 59.90m,
                            Stock = 110,
                            SubCategoryId = 10
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2026, 4, 14, 20, 59, 38, 489, DateTimeKind.Local).AddTicks(9946),
                            FotoPath = "images/comedy_homealone.jpg",
                            IsActive = true,
                            Name = "Komedi Filmi - Home Alone",
                            Price = 64.90m,
                            Stock = 130,
                            SubCategoryId = 10
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2026, 4, 14, 20, 59, 38, 489, DateTimeKind.Local).AddTicks(9948),
                            FotoPath = "images/tiyatro_trajedi_oidipus.jpg",
                            IsActive = true,
                            Name = "Trajedi Oyunu - Kral Oidipus",
                            Price = 99.90m,
                            Stock = 50,
                            SubCategoryId = 11
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2026, 4, 14, 20, 59, 38, 489, DateTimeKind.Local).AddTicks(9950),
                            FotoPath = "images/tiyatro_komedi_yazgecesi.jpg",
                            IsActive = true,
                            Name = "Komedi Oyunu - Bir Yaz Gecesi Rüyası",
                            Price = 79.90m,
                            Stock = 70,
                            SubCategoryId = 12
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2026, 4, 14, 20, 59, 38, 489, DateTimeKind.Local).AddTicks(9952),
                            FotoPath = "images/tiyatro_dram_hamlet.jpg",
                            IsActive = true,
                            Name = "Dram Oyunu - Hamlet",
                            Price = 89.90m,
                            Stock = 60,
                            SubCategoryId = 13
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2026, 4, 14, 20, 59, 38, 489, DateTimeKind.Local).AddTicks(9954),
                            FotoPath = "images/tiyatro_muzikli_lesmis.jpg",
                            IsActive = true,
                            Name = "Müzikli Tiyatro - Les Misérables",
                            Price = 119.90m,
                            Stock = 40,
                            SubCategoryId = 14
                        });
                });

            modelBuilder.Entity("EMedia.Models.ProductComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductComments");
                });

            modelBuilder.Entity("EMedia.Models.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            IsActive = true,
                            Name = "Pop"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            IsActive = true,
                            Name = "Rock"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            IsActive = true,
                            Name = "Jazz"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            IsActive = true,
                            Name = "Blues"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            IsActive = true,
                            Name = "Klasik"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            IsActive = true,
                            Name = "Metal"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            IsActive = true,
                            Name = "Reggae"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            IsActive = true,
                            Name = "Aksiyon"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            IsActive = true,
                            Name = "Dram"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            IsActive = true,
                            Name = "Komedi"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            IsActive = true,
                            Name = "Trajedi"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            IsActive = true,
                            Name = "Komedi"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            IsActive = true,
                            Name = "Dram"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            IsActive = true,
                            Name = "Müzikli Tiyatro"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            IsActive = true,
                            Name = "Klasik Müzik Konserleri"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            IsActive = true,
                            Name = "Halk Müziği Konserleri"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            IsActive = true,
                            Name = "Akustik Konserler"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            IsActive = true,
                            Name = "Pop Konserleri"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            IsActive = true,
                            Name = "Rock Konserleri"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            IsActive = true,
                            Name = "Jazz Konserleri"
                        });
                });

            modelBuilder.Entity("EMedia.Models.Product", b =>
                {
                    b.HasOne("EMedia.Models.SubCategory", "SubCategory")
                        .WithMany("Products")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("EMedia.Models.ProductComment", b =>
                {
                    b.HasOne("EMedia.Models.Comment", "Comment")
                        .WithMany("ProductComments")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMedia.Models.Product", "Product")
                        .WithMany("ProductComments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EMedia.Models.SubCategory", b =>
                {
                    b.HasOne("EMedia.Models.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EMedia.Models.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("EMedia.Models.Comment", b =>
                {
                    b.Navigation("ProductComments");
                });

            modelBuilder.Entity("EMedia.Models.Product", b =>
                {
                    b.Navigation("ProductComments");
                });

            modelBuilder.Entity("EMedia.Models.SubCategory", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
